name: Releases

on: 
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.16.0'
          registry-url: https://registry.npmjs.org/

      - name: "Install, build and zip"
        run: |
          cd az-function
          npm ci
          cd ..
          npm run build
          npm prune --omit=dev
          zip -r app.zip . --exclude @.funcignore --exclude .funcignore
# create a zip that can be deployed to Azure
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "app.zip"
          # token: ${{ secrets.YOUR_GITHUB_TOKEN }}